export const EVENTS = {
	CREATE_USER: 'CREATE_USER',
	INIT_BALANCE: 'INIT_BALANCE',
	GET_ACTIVE_MARKETS: 'GET_ACTIVE_MARKETS',
	GET_MARKET_WITH_SYMBOL: 'GET_MARKET_WITH_SYMBOL',
	PLACE_ORDER: 'PLACE_ORDER',
	CANCEL_ORDER: 'CANCEL_ORDER',
	SELL_ORDER: 'SELL_ORDER',
};

export const ROLE = 'BOT';
